### ISSUE TITLE
I f***ing hate gulp

### ISSUE THREAD

**Issue by nscarcella** [uqbar-project/wollok-js#16]
There. I said it.

Defining task sequence is a mess, even when we only have a really simple build process. Plus we have a million dependencies just gulp-related that only end up running some basic console command anyway, and most of the tasks are just there so we can run them in sequence instead of in parallel...

I need to rewire the build process so the WRE is properly compiled and all tests are run against /dist and I've been postponing it for days because I know it's going to be ugly.

I would be so much happier if we could replace the whole gulp mambo-jambo with a couple of small yarn tasks. I understand there are CI reasons why we need gulp, but I'll be glad to investigate if there is some other way.

What do you think, @javierfernandes?

**Comment by javierfernandes** [comment]
Yeap, no problem.

In general I found that as long as your needs are already fulfilled by a gulp-xxx package then gulp is nice, the problem is when you want to do your own plugin, working with the streams pipeline is horrifying.

To run tasks in sequence there is a  'seq' package I believe.
Anyway, if you want to remove it then go ahead. I was only using it to make travis fail for eslint errors. Just running it from yarn didn't return the appropiated error code :( and build was successful even if the lint failed

**Comment by nscarcella** [comment]
It seems like jenkins and yarn fail just fine as long as the lint problem is an error (not a warning), so I will remove gulp and we can make the lint more rigorous if needed.
